site_name: TrackFlow Documentação Dashboards e Automações

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.action.edit
    - content.action.view
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  language: pt
  logo: images/logo.png
  favicon: images/favicon.ico
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search:
      lang: pt
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2:
      arguments:
        theme: default
        flowchart:
          useMaxWidth: true
        themeVariables:
          primaryColor: '#2196F3'
          primaryTextColor: '#ffffff'
          primaryBorderColor: '#1976D2'
          lineColor: '#424242'
          sectionBkColor: '#E3F2FD'
          altSectionBkColor: '#BBDEFB'
          gridColor: '#E0E0E0'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Nesta página
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - style/extra.css
  - style/custom_colors.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra:
  homepage: https://trackflow.com.br
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trackflow
      name: TrackFlow no GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/trackflow
      name: TrackFlow no LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:contato@trackflow.com.br
      name: Contato
  version:
    provider: mike
    default: latest
  generator: false

copyright: |
  &copy; 2025 <a href="https://trackflow.com.br" target="_blank" rel="noopener">TrackFlow</a> - 
  Todos os direitos reservados

nav:
  - Início: index.md
  - Para GC:
    - Rotinas: 
      - Controle e agendamento de inspeções: gc/rotinas/index.md
    - Consulta de dados: 
      - Tabela resumo: gc/resumo/index.md
  - Para PCP:
    - Dashboards: pcp/dashboards/index.md
    - Automações: pcp/automacoes/index.md
    - Análise e controle MAPA: pcp/reuniao_mapa/index.md
    - Gerar Mapa: pcp/gerar_mapa/index.md
    - Justificativas: pcp/justificativas/index.md
  - Para Comercial:
    - Para Usuários:
      - Início: comercial/para_usuarios/index.md
      - Consultas: comercial/para_usuarios/consulta.md
      - Cadastros: comercial/para_usuarios/cadastro.md
      - Edição: comercial/para_usuarios/edicao.md
      - Revisões: 
        - Visão Geral: comercial/para_usuarios/revisao.md 
        - Proposta Automatizada para Transformadores: comercial/para_usuarios/proposta_trafo.md
        - Proposta Automatizada para Solar: comercial/para_usuarios/proposta_solar.md
      - Follows: comercial/para_usuarios/follow.md
  - Para Laboratório:
    - Início: lab/rotinas/index.md
    - Controle de Inspeções: lab/rotinas/inspecao.md
    - Apontamento de Data de Fabricação: lab/rotinas/apontamento_dt_fab.md
  - Para Qualidade:
    - Início: qualidade/rotinas/index.md
    - Controle de OS: qualidade/rotinas/controle_os.md