site_name: TrackFlow Documentação Dashboards e Automações

theme:
  name: readthedocs
  features:
      - navigation.tabs 
      - navigation.sections 
      - navigation.expand 
      - navigation.top 
      - content.code.copy 
      - content.code.annotate 
      - content.action.edit 
      - content.action.view 
      - content.action.print
      - search.suggest 
      - search.highlight 
      - search.share 
  language: pt
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  pallete:
    - scheme: default
      primary: blue-grey
      accent: indigo
    - scheme: slate
      primary: black
      accent: black

extra_css: 
  - style/extra.css

nav:
  - Início: index.md
  - Para PCP:
    - Dashboards: pcp/dashboards/index.md
    - Automações: pcp/automacoes/index.md
    - Gerar Mapa: pcp/gerar_mapa/index.md
    - Justificativas: pcp/justificativas/index.md

