site_name: TrackFlow Documentação Dashboards e Automações
extra_css: 
  - docs\style\extra.css

theme:
  name: readthedocs
  features:
      - navigation.tabs 
      - navigation.sections 
      - navigation.expand 
      - navigation.top 
      - content.code.copy 
      - content.code.annotate 
      - content.action.edit 
      - content.action.view 
      - content.action.print
      - search.suggest 
      - search.highlight 
      - search.share 
  language: pt
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  pallete:
    - scheme: default
      primary: blue-grey
      accent: indigo
    - scheme: slate
      primary: black
      accent: black



nav:
  - Início: index.md
  - Para GC:
    - Rotinas: 
      - Controle e agendamento de inspeções: gc/rotinas/index.md
  - Para PCP:
    - Dashboards: pcp/dashboards/index.md
    - Automações: pcp/automacoes/index.md
    - Gerar Mapa: pcp/gerar_mapa/index.md
  - Para Comercial:
    - Para Usuários:
      - Início: comercial/para_usuarios/index.md
      - Consultas: comercial/para_usuarios/consulta.md
      - Cadastros: comercial/para_usuarios/cadastro.md
      - Edição: comercial/para_usuarios/edicao.md
      - Revisões: 
        - Visão Geral: comercial/para_usuarios/revisao.md 
        - Proposta Automatizada para Transformadores: comercial/para_usuarios/proposta_trafo.md
        - Proposta Automatizada para Solar: comercial/para_usuarios/proposta_solar.md
      - Follows: comercial/para_usuarios/follow.md
    - Para Desenvolvedores: comercial/para_desenvolvedores/index.md

